### ISSUE TITLE
Incompatible dependencies

### ISSUE THREAD

**Issue by macabeus** [syncfusion/flutter-widgets#16]
I'm trying to upgrade Flutter version on my project, but looks like that there are incompatible dependencies on the project:
```
Because test >=1.16.0-nullsafety.5 depends on pedantic >=1.10.0-nullsafety <1.10.0 and syncfusion_flutter_core >=18.2.54 depends on pedantic >=1.9.0 <1.9.9, test >=1.16.0-nullsafety.5 is incompatible with syncfusion_flutter_core >=18.2.54.
```

How could I solve that?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @macabeus,

Thanks for contacting Syncfusion Support. We have analyzed your query and we tried to replicate the reported issue regarding version solving errors with the latest flutter SDK version and we are not able to replicate the reported issue at our end. So, we kindly request you to share us with the Flutter SDK version which you are using in your machine to build Flutter App projects and also the other dependencies which you are using in your Flutter project along with our Sycnfusion flutter widgets(i.e., share us your project's dependencies you have used in the pubspec.yaml file). This will be helpful in providing the solutions sooner.

Regards,
Sriram Kiran

**Comment by SogoGolf** [comment]
yes this is a bit of a nightmare, we are still having problems on **flutter stable channel** and can not build our project if we include syncfusion (without it is fine).

please assist as we rely on syncfusion grid and charts now. a sample pubspec.yaml is attached.
[pubspec.yaml.zip](https://github.com/syncfusion/flutter-widgets/files/5375943/pubspec.yaml.zip)


```
➜ fvm flutter doctor -v
FVM: Running version 1.22.1
[✓] Flutter (Channel unknown, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-AU)
    • Flutter version 1.22.1 at /Users/angusjohnston/fvm/versions/1.22.1
    • Framework revision f30b7f4db9 (6 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/angusjohnston/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

• No issues found!
```

**Comment by jamesdixon** [comment]
I'm also running into the same issue, specifically when attempting to run `flutter drive`. 

I'm using Flutter Stable, `1.22.1` but also saw this on `1.22.0`.

Here's my `pubspec.yaml`:

```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_data:
    git:
      url: https://github.com/flutterdata/flutter_data.git
      ref: 0.5.5
  flutter_data_json_api_adapter:
    git:
      url: https://github.com/flutterdata/flutter_data_json_api_adapter.git
      ref: 0.1.3
  flutter_data_state:
    git:
      url: https://github.com/flutterdata/data_state.git
      path: packages/flutter_data_state
      ref: 0.3.6
  map_launcher:
    git:
      url: git://github.com/scoutforpets/map_launcher.git
      ref: master
  auto_route: ^0.6.7
  flutter_easyrefresh: ^2.1.5
  flutter_hooks: ^0.14.1
  flutter_secure_storage: ^3.3.4
  flutter_vibrate: ^1.0.0
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  hooks_riverpod: ^0.11.1
  http: ^0.12.2
  intl: ^0.16.1
  json_annotation: ^3.0.1
  path_provider: ^1.6.7
  syncfusion_flutter_datepicker: ^18.3.35-beta
  url_launcher: ^5.7.2
  validators: ^2.0.1

# temp fix for auto_route issues
# https://github.com/Milad-Akarie/auto_route_library/issues/250#issuecomment-702769836
dependency_overrides:
  analyzer: "0.39.15"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test:
  auto_route_generator: ^0.6.8
  build_runner: ^1.10.0
  freezed: ^0.11.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/config.json
```

I can confirm that removing the date picker fixes the issue.
