### ISSUE TITLE
[syncfusion_flutter_charts] `TrackballBehavior#builder` throws Exception when series have differing lengths

### ISSUE THREAD

**Issue by btrautmann** [syncfusion/flutter-widgets#1752]
I have a chart that consists of a `LineSeries`, a `StepLineSeries`, and another `LineSeries`. The `StepLineSeries` tracks spending in the current month, and therefore may not be the same length as the "limit" and "projected spend" `LineSeries` (in fact, on all days but the last of the month, it will not be).

Scrubbing on the chart to show the tooltip for `TrackballBehavior` causes an `Exception` when scrolling beyond the length of the series. I thought it might be in my code but it appears to occur even before `builder` is called.

I can try to put together a reproducible sample if needed, just let me know. I'm hoping the screenshot and console output would be sufficient here.

![Screenshot 2024-03-20 at 06 34 42](https://github.com/syncfusion/flutter-widgets/assets/8343465/35d75ca4-4db0-41ea-a3e8-7148c0ffde37)

```
  syncfusion_flutter_charts:
    dependency: "direct main"
    description:
      name: syncfusion_flutter_charts
      sha256: ab73109c586f5ec2b01adc2672026a1fb3f93b2b5f6061ba8d7126c119061002
      url: "https://pub.dev"
    source: hosted
    version: "24.2.9"
```

```
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale en-US)
    • Flutter version 3.19.3 on channel stable at /Users/brandontrautmann/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (13 days ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1
```
