### ISSUE TITLE
syncfusion_flutter_charts library is having versioning issues

### ISSUE THREAD

**Issue by yashwp** [syncfusion/flutter-widgets#35]
Library version -   `syncfusion_flutter_charts: ^18.3.44`

```
The current Dart SDK version is 2.10.2.

Because every version of flutter_test from sdk depends on test_api 0.2.19-nullsafety.2 and test >=1.15.3 <1.16.0-nullsafety depends on test_api 0.2.18, flutter_test from sdk is incompatible with test >=1.15.3 <1.16.0-nullsafety.
Because test >=1.16.0-nullsafety <1.16.0-nullsafety.5 requires SDK version >=2.10.0-0 <2.10.0 and test >=1.16.0-nullsafety.5 depends on pedantic >=1.10.0-nullsafety <1.10.0, test >=1.16.0-nullsafety requires pedantic >=1.10.0-nullsafety <1.10.0.
Thus, if flutter_test any from sdk and test >=1.15.3 then pedantic >=1.10.0-nullsafety <1.10.0.
And because syncfusion_flutter_core >=18.2.54 depends on pedantic >=1.9.0 <1.9.9, one of flutter_test any from sdk or test >=1.15.3 or syncfusion_flutter_core >=18.2.54 must be false.
And because stack_app depends on syncfusion_flutter_charts ^18.3.44 which depends on syncfusion_flutter_core ^18.3.44, flutter_test from sdk is incompatible with test >=1.15.3.
So, because stack_app depends on both flutter_test any from sdk and test ^1.15.4, version solving failed.
pub get failed (1; So, because stack_app depends on both flutter_test any from sdk and test ^1.15.4, version solving failed.)
Process finished with exit code 1
```

Here is the output of `flutter doctor -v`

```
$ flutter doctor -v
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.2 at C:\Users\yash\flutter
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\yash\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\yash\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\yash\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1
```

**Comment by yashwp** [comment]
As a workaround, I have to comment out `flutter_test` from `pubspec.yml`

**Comment by SriramKiranSenthilkumar** [comment]
Hi @yashwp,

Greetings from Syncfusion. We have analyzed your scenario with the provided information and we tried to replicate the reported version solving issues at our end. Unfortunately, we are not able to replicate the reported issue at our end. On further analysis,  we found that the version solving issues mentioned in the query is due to the flutter test plugin using the presale version of the pedantic package([1.10.0-nullsafety](https://pub.dev/packages/pedantic/versions/1.10.0-nullsafety)) and as we do not provide support for presale versions, we cannot update the pedantic package to its presale version. However, to overcome the reported version solving issue, kindly please add the below code in your Flutter project's pubspec.yaml file.
```
dependency_overrides:
  pedantic: 1.10.0-nullsafety
```
For further reference on how to add dependency overrides for your Flutter project, please click [here](https://dart.dev/tools/pub/dependencies#dependency-overrides)

Regards,
Srirram Kiran

**Comment by darek607** [comment]
The same happened to me. Hopefully adding `pedantic: 1.10.0-nullsafety` to dependency_overrides solved the issue.

My project's config:

`Flutter 1.22.4 • channel stable`

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.1
  firebase_analytics: ^6.0.1
  intl: ^0.16.1
  bloc: ^6.0.2
  flutter_bloc: ^6.0.1
  equatable: ^1.2.4
  flutter_svg: ^0.18.1
  flutter_widget_from_html: ^0.5.0+6
  get_it: ^4.0.4
  cached_network_image: 2.2.0+1
  shared_preferences: ^0.5.10
  dio: ^3.0.10
  oauth_dio: ^0.1.2
  environment_config: ^2.2.3
#  flutter_staggered_grid_view: ^0.3.2
  flutter_staggered_grid_view:
    git:
      url: https://github.com/BertrandBev/flutter_staggered_grid_view.git
  package_info: ^0.4.3
#  QR library fork with specified commit that fixes the TrustManager vulnerability in Google Play.
#  The library is also included in the project folder.
#  https://github.com/rhymelph/r_scan/issues/32
  r_scan:
    git:
      url: https://github.com/ARRO-Coffee/r_scan.git
      ref: 82bb8e3d400bb73c5243c58c90c1ec7236d478bd
  pin_code_fields: ^5.1.0
  local_auth: ^0.6.3+1
  syncfusion_flutter_charts: ^18.3.40
  quiver: ^2.1.3
  pretty_dio_logger: ^1.1.1
  datetime_picker_formfield: ^1.0.0
  url_launcher: ^5.1.3
  webview_flutter: ^0.3.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.5
  bloc_test: ^7.0.0
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  flutter_launcher_icons: ^0.7.5
  pedantic: ^1.9.0
  freezed: ^0.11.2
```
