### ISSUE TITLE
syncfusion_flutter_datepicker breaks my dependency tree for integration tests

### ISSUE THREAD

**Issue by ajaygautam** [syncfusion/flutter-widgets#89]
I am adding integration tests to my project, but `syncfusion_flutter_datepicker` does not let me include `integration_test`

I have to comment out one OR the other to get this working. Please fix this ASAP.

`flutter pub get` fails with:

```
The current Dart SDK version is 2.12.0-29.10.beta.                      
                                                                        
Because no versions of syncfusion_flutter_datepicker match >18.3.53-beta <19.0.0 and syncfusion_flutter_datepicker 18.3.53-beta depends on syncfusion_flutter_core ^18.3.53, syncfusion_flutter_datepicker ^18.3.53-beta requires syncfusion_flutter_core ^18.3.53.
And because no versions of syncfusion_flutter_core match >18.3.53 <19.0.0, syncfusion_flutter_datepicker ^18.3.53-beta requires syncfusion_flutter_core 18.3.53.
And because syncfusion_flutter_core 18.3.53 depends on pedantic >=1.9.0 <1.9.9 and test >=1.16.0-nullsafety.7 depends on pedantic >=1.10.0-nullsafety <1.10.0, syncfusion_flutter_datepicker ^18.3.53-beta is incompatible with test >=1.16.0-nullsafety.7.
Because no versions of test match >1.15.7 <1.16.0-nullsafety and test >=1.16.0-nullsafety <1.16.0-nullsafety.7 requires SDK version >=2.10.0-0 <2.11.0, test >1.15.7 <1.16.0-nullsafety.7 is forbidden.
Thus, syncfusion_flutter_datepicker ^18.3.53-beta is incompatible with test >1.15.7.
And because test 1.15.7 depends on test_api 0.2.18+1 and every version of flutter_test from sdk depends on test_api 0.2.19-nullsafety.6, one of syncfusion_flutter_datepicker ^18.3.53-beta or test >=1.15.7 or flutter_test any from sdk must be false.
And because every version of integration_test depends on flutter_test any from sdk and aip depends on syncfusion_flutter_datepicker ^18.3.53-beta, test >=1.15.7 is incompatible with integration_test.
So, because aip depends on both integration_test ^1.0.1 and test ^1.15.7, version solving failed.
Running "flutter pub get" in aip_app...                                 
pub get failed (1; So, because aip depends on both integration_test ^1.0.1 and test ^1.15.7, version solving
failed.)
```

My buildspec.yaml:
```
name: aip
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  cupertino_icons: ^1.0.0
  local_auth: ^0.6.3+4
  flutter_platform_widgets: ^0.70.2
  page_transition: "^1.1.7+2"
  flutter_keyboard_visibility: ^4.0.2
  email_validator: '^1.0.5'
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  get_it: ^5.0.1
  logging: ^0.11.4
  shared_preferences: ^0.5.12+4
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  after_layout: 1.0.7+2
  flutter_secure_storage: ^3.3.5
  sentry: ">=3.0.0 <4.0.0"
  fluttertoast: ^7.1.3
  syncfusion_flutter_datepicker: ^18.3.53-beta
  intl: ^0.16.1
  json_annotation: ^3.1.1
  localstorage: ^3.0.0
  firebase_performance: ^0.4.3
  # For command line scripts
  args: ^1.6.0
  csv: ^4.1.0

dev_dependencies:
  integration_test: ^1.0.1
  test: ^1.15.7
  json_serializable: ^3.5.0
  build_runner: ^1.0.0
  rename: ^1.2.0
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  image: assets/images/aio-splash-screen.png
  color: "23252A"
  fill: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-app.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/text/
```

flutter doctor -v
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-arm, locale en-US)
    • Flutter version 1.24.0-10.2.pre at /Users/agautam/tools/flutter
    • Framework revision 022b333a08 (4 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/agautam/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • D52F7EE5-34D4-4444-B05E-743F72B240A9 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

• No issues found!
```
