### ISSUE TITLE
[syncfusion_flutter_datagrid] SfDataPager will slow or even crash when update the widget pageCount

### ISSUE THREAD

**Issue by East333** [syncfusion/flutter-widgets#891]
When I use StatefulBuilder or FutureBuilder to update pageCount of SfDataPager，if previous pageCount <= SfDataPager.visibleItemsCount (defualt is 5), the SfDataPager will build every page button, if next pageCount is 10000, the program will slow or even crash,
and cpu is High Occupanncy Toll
[cpu_hot_picture](http://tva1.sinaimg.cn/large/9b6fad93ly1h6e8agncbrj218h19ah8l.jpg)
Platform: Windows, MacOS
the code example is:
```dart
        FutureBuilder<double>(
          future: () async {
            await Future<void>.delayed(Duration(seconds: 1));
            return 10000.0;
          }(),
          builder: (context, snapshot) {
            switch (snapshot.connectionState) {
              case ConnectionState.none:
                return const Text('Press button to start');
              case ConnectionState.waiting:
                return SfDataPager(
                  itemHeight: hiPagerItemHeight(),
                  itemWidth: hiPagerItemHeight(),
                  navigationItemHeight: hiPagerItemHeight(),
                  navigationItemWidth: hiPagerItemHeight(),
                  itemPadding: const EdgeInsets.all(2),
                  controller: dataPagerController,
                  availableRowsPerPage: Constants.instance.availableRowsPerPage,
                  delegate: orderContractSourceView,
                  pageCount: 1,
                  direction: Axis.horizontal,
                  onRowsPerPageChanged: onRowsPerPageChanged,
                );
              default:
                if (snapshot.hasError) {
                  return Text('Error: ${snapshot.error}');
                } else {
                  return SfDataPager(
                    itemHeight: hiPagerItemHeight(),
                    itemWidth: hiPagerItemHeight(),
                    navigationItemHeight: hiPagerItemHeight(),
                    navigationItemWidth: hiPagerItemHeight(),
                    itemPadding: const EdgeInsets.all(2),
                    controller: dataPagerController,
                    availableRowsPerPage: Constants.instance.availableRowsPerPage,
                    delegate: orderContractSourceView,
                    pageCount: snapshot.data!,
                    direction: Axis.horizontal,
                    onRowsPerPageChanged: onRowsPerPageChanged,
                  );
                }
            }
          },
        ),
```
please fix the problem or tell me the correct way to update the SfDataPager.pageCount
thanks

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @East333,


Thank you for your patience. We have checked your query at our end, and we are able to replicate the reported issue at our end. We have considered this as a bug and logged a bug report regarding this in our feedback portal.

We will fix the reported issue and include the changes in our upcoming weekly patch release which is expected to be rolled out on October 11, 2022 . We will update you once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug using the feedback link below.

Feedback Link: https://www.syncfusion.com/feedback/38053/sfdatapager-is-not-working-properly-when-updating-the-pagecount-dynamically 

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @East333,

We are glad to inform you that the fix has been included in our weekly pub release for the mentioned issue. Please update the DataGrid package to version 20.3.49.

https://pub.dev/packages/syncfusion_flutter_datagrid/changelog 

We thank you for your support and appreciate your patience in waiting for this update. Please get in touch with us if you require any further assistance.

Regards,  
Tamilarasan

**Comment by East333** [comment]
I'm glad to hear your new version, but I have new problem after install 20.3.49, the error message is 
```
Launching lib/main.dart on macOS in debug mode...
Running pod install...
Building macOS application...
../../Src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.3.49/lib/src/datagrid_widget/widgets/cell_widget.dart:733:23: Error: 'PointerEnterEvent' isn't a type.
            onEnter: (PointerEnterEvent details) {
                      ^^^^^^^^^^^^^^^^^
../../Src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.3.49/lib/src/datagrid_widget/widgets/cell_widget.dart:738:22: Error: 'PointerExitEvent' isn't a type.
            onExit: (PointerExitEvent details) {
                     ^^^^^^^^^^^^^^^^

Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Exception: Build process failed
```

Platform: Macos 12.4
Flutter 3.0.5 • channel stable 
Dart 2.17.6 • DevTools 2.12.2

the package version is:
```
  syncfusion_flutter_core:
    dependency: transitive
    description:
      name: syncfusion_flutter_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "20.3.49"
  syncfusion_flutter_datagrid:
    dependency: "direct main"
    description:
      name: syncfusion_flutter_datagrid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "20.3.49"
  syncfusion_flutter_datepicker:
    dependency: "direct main"
    description:
      name: syncfusion_flutter_datepicker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "20.3.49"
  syncfusion_localizations:
    dependency: "direct main"
    description:
      name: syncfusion_localizations
      url: "https://pub.dartlang.org"
    source: hosted
    version: "20.3.49"
```

Looking forward to your reply.
